### ISSUE TITLE
UnhandledPromiseRejectionWarning: HttpError: Invalid request.

### ISSUE THREAD

**Issue by hebertdougl** [deblockt/cucumber-report-annotations-action#26]
I'm trying to run this action with json file, but in my tests I get `HttpError Invalid request`error. Would you know what this error would be?
```
10 Scenarios (1 failed, 9 passed)
    56 Steps (4 failed, 6 skipped, 46 passed)
send global cucumber report data
(node:2201) UnhandledPromiseRejectionWarning: HttpError: Invalid request.

"end_line", "start_line" weren't supplied.
    at /home/runner/work/_actions/deblockt/cucumber-report-annotations-action/v1.7/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/runner/work/_actions/deblockt/cucumber-report-annotations-action/v1.7/index.js:1[54](https://github.com/grafeno-sa/grafeno-pagamentos/runs/5142723681?check_suite_focus=true#step:4:54):9
(node:2201) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2201) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by deblockt** [comment]
It seem that on your cucumber report JSON, step in error are not linked with a line. 
For example, when a step is in error there is the following JSON on the report on `elements.steps`:
```
{
            "arguments": [],
            "keyword": "Given ",
            "line": 4,
            "name": "this step will fail",
            "match": {
              "location": "cucumber/step-definitions/stepdefs.js:4"
            },
            "result": {
              "status": "failed",
              "duration": 2000000,
              "error_message": "AssertionError [ERR_ASSERTION]: this step allways fail\n    at World.<anonymous> (/Users/deblockt/Documents/projects/opensource/cucumber-report-annotations-action/cucumber/step-definitions/stepdefs.js:5:12)"
            }
          }
```

You can see that the property `line` is set. In you can it seem that this property is missing. 
Can you check if the `line` property is set or not? Maybe that you can past a part of your JSON report to analyse it. 

what language do you use?

**Comment by hebertdougl** [comment]
Hi @deblockt, thanks for you response. I'm using ruby language with rails framework. 
```
{
   "uri": "features/specifications/example.feature",
   "id": "my-feature-id",
   "keyword": "",
   "name": "",
   "description": "",
   "line": 7,
   "tags": [
        {
            "name": "@name_test",
            "line": 5
        }
    ],
   "comments":[
      {
         "value": "# frozen_string_literal: true",
         "line": 1
      }
   ],
   "elements": [
        {
                "keyword": "Contexto",
                "name": "Test",
                "description": "",
                "line": 13,
                "type": "background",
                "before": [
                    {
                        "match": {
                            "location": "vendor/bundle/ruby/2.7.0/gems/capybara-3.35.3/lib/capybara/cucumber.rb:14"
                        },
                        "result": {
                            "status": "passed",
                            "duration": 20400
                        }
                      }
                ],
                "steps": [
                    {
                          "keyword": "When ",
                          "name": "my test step",
                          "line": 14,
                          "match": {
                              "location": "features/step_definitions/test_steps.rb:7"
                          },
                          "result": {
                              "status": "passed",
                              "duration": 701680260
                          }
                    }
              ]
        }
  ]
}
```
The property `line` is set, but I note that in your example exists the key `arguments` but this key is missing in my example. The rest of the keys seem correct to me. Do you think this could be the problem?

**Comment by deblockt** [comment]
Hi @hebertdougl I tried to reproduce you issue on this check https://github.com/deblockt/cucumber-report-annotations-action/runs/5244351314?check_suite_focus=true but all works fine. 
I'm curious to see your full cucumber.json file. 

I can add a condition before creating annotation (create the annotation only if line is present), but it can be complicated to understand if the check is failed without annotation :s

**Comment by deblockt** [comment]
I created a PR https://github.com/deblockt/cucumber-report-annotations-action/pull/31 to fix the issue.
@hebertdougl Can you try to use the branche `fix/issue26`? 
This branch don't fix the root cause, but set the line to 0 if the line can not be found on cucumber report.

**Comment by deblockt** [comment]
closed due to inactivity
