### ISSUE TITLE
error: RequestError [HttpError]: Resource not accessible by integration

### ISSUE THREAD

**Issue by xyuste** [deblockt/cucumber-report-annotations-action#44]
Hi
I have this error trying to use the cucumber-report-annotations-action@v1.7
Do you know what is the problem?

Run deblockt/cucumber-report-annotations-action@v1.7
start to read cucumber logs using path target/cucumber.json
found cucumber report /home/runner/work/ovr-automationTestUI/ovr-automationTestUI/target/cucumber.json
{
  scenarioNumber: 1,
  failedScenarioNumber: 0,
  undefinedScenarioNumber: 0,
  pendingScenarioNumber: 0,
  succeedScenarioNumber: 1,
  stepsNumber: 5,
  failedStepsNumber: 0,
  skippedStepsNumber: 0,
  undefinedStepsNumber: 0,
  pendingStepNumber: 0,
  succeedStepsNumber: 5
}
    1 Scenarios (1 passed)
    5 Steps (5 passed)
send global cucumber report data
/home/runner/work/_actions/deblockt/cucumber-report-annotations-action/v1.7/node_modules/@octokit/request/dist-node/index.js:66
        const error = new requestError.RequestError(message, status, {
                      ^

RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/deblockt/cucumber-report-annotations-action/v1.7/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/runner/work/_actions/deblockt/cucumber-report-annotations-action/v1.7/index.js:154:9 {
  status: 403,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Tue, 25 Jul 2023 11:27:29 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-api-version-selected': '2022-11-28',
    'x-github-media-type': 'github.v3; param=antiope-preview; format=json',
    'x-github-request-id': '[14](https://github.com/xyuste/ovr-automationTestUI/actions/runs/5656183843/job/15322711072#step:6:15)80:2484:16A9CC:2DDDB4:64BFB1A1',
    'x-ratelimit-limit': '1000',
    'x-ratelimit-remaining': '996',
    'x-ratelimit-reset': '1690287088',
    'x-ratelimit-resource': 'core',
    'x-ratelimit-used': '4',
    'x-xss-protection': '0'
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/xyuste/ovr-automationTestUI/check-runs',
    headers: {
      accept: 'application/vnd.github.antiope-preview+json',
      'user-agent': 'octokit-core.js/3.1.0 Node.js/16.16.0 (Linux 5.[15](https://github.com/xyuste/ovr-automationTestUI/actions/runs/5656183843/job/15322711072#step:6:16); x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"name":"Cucumber report","head_sha":"37d666c57f1f7ed2d3[22](https://github.com/xyuste/ovr-automationTestUI/actions/runs/5656183843/job/15322711072#step:6:23)dc7977591bc397745c9c","status":"completed","conclusion":"success","output":{"title":"Cucumber report","summary":"    1 Scenarios (1 passed)\\n    5 Steps (5 passed)","annotations":[{"path":"test","start_line":0,"end_line":0,"start_column":0,"end_column":0,"annotation_level":"notice","title":"Cucumber report summary","message":"    1 Scenarios (1 passed)\\n    5 Steps (5 passed)"}]}}',
    request: {
      agent: Agent {
        _events: [Object: null prototype] {
          free: [Function (anonymous)],
          newListener: [Function: maybeEnableKeylog]
        },
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object: null prototype] { path: null },
        requests: [Object: null prototype] {},
        sockets: [Object: null prototype] {},
        freeSockets: [Object: null prototype] {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: [25](https://github.com/xyuste/ovr-automationTestUI/actions/runs/5656183843/job/15322711072#step:6:26)6,
        scheduling: 'lifo',
        maxTotalSockets: Infinity,
        totalSocketCount: 0,
        maxCachedSessions: 100,
        _sessionCache: {
          map: {
            'api.github.com:4[43](https://github.com/xyuste/ovr-automationTestUI/actions/runs/5656183843/job/15322711072#step:6:44):::::::::::::::::::::': [Buffer [Uint8Array]]
          },
          list: [ 'api.github.com:[44](https://github.com/xyuste/ovr-automationTestUI/actions/runs/5656183843/job/15322711072#step:6:45)3:::::::::::::::::::::' ]
        },
        [Symbol(kCapture)]: false
      },
      hook: [Function: bound bound register]
    }
  },
  documentation_url: 'https://docs.github.com/rest/checks/runs#create-a-check-run'
}

I have the following yml file in the github / workflows 
name: Java CI with Maven

on:
    workflow_dispatch:
      inputs:
        tags:
          description: Cucumber tags
          type: string
          default: TEST
          required: true

jobs:
  build:

    permissions:
      actions: read
      contents: read
      security-events: write
      statuses: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean test -Denvironment=t1 -Dbrowser=remote4 -Dcucumber.filter.tags="@${{ inputs.tags }}"
    - name: Upload Cucumber Report
      uses: actions/upload-artifact@v2
      with:
        name: cucumber-report
        path: target/cucumber/reports/cucumber-html-reports

    - uses: deblockt/cucumber-report-annotations-action@v1.7
      with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "target/cucumber.json"

**Comment by xyuste** [comment]
Sorry it has been an error on my side,
Now it works correctly
Thanks

**Comment by xyuste** [comment]
I close the issue

**Comment by xyuste** [comment]
It has been an error on my side
Regards
